# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b6c35f1f28ca75c5a862b0a79daaaddd"
name = "merchant-quote"
application_url = "https://merchant-quote-app.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "fidetechnologies-2.myshopify.com"

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks"
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,read_customers,write_draft_orders,write_products,read_themes,write_content,read_content"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://merchant-quote-app.fly.dev/api/auth/callback"]

[app_proxy]
url = "https://merchant-quote-app.fly.dev/api"
subpath = "request-quote"
prefix = "apps"

[pos]
embedded = true

[shop.metafields.app.show_on_all]
name = "Show quote globally"
type = "boolean"

[shop.metafields.app.show_on_all.access]
admin = "merchant_read_write"
storefront = "public_read"
