import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Bundles the theme extension JS files into a single file for production.
 * This reduces the number of network requests and improves Lighthouse scores.
 */

const assetsDir = 'extensions/quote/assets';
const outputFile = join(assetsDir, 'request-quote.bundle.js');

const filesToBundle = [
  'rq-api.js',
  'rq-cart.js',
  'rq-ui.js',
  'rq-validation.js',
  'request-quote.js'
];

function bundle() {
  console.log('⚡ Starting theme extension bundle...');

  let bundledContent = `/**
 * Merchant Quote - Bundled Extension Asset
 * Generated on: ${new Date().toISOString()}
 * 
 * This file is automatically generated by scripts/build-theme-extension.ts
 * DO NOT EDIT THIS FILE DIRECTLY. Edit the individual files in ${assetsDir}/ instead.
 */\n`;

  for (const fileName of filesToBundle) {
    const filePath = join(assetsDir, fileName);
    if (existsSync(filePath)) {
      console.log(`  + Adding ${fileName}`);
      const content = readFileSync(filePath, 'utf8');

      // We wrap in a comment block to help with debugging the bundle if needed
      bundledContent += `\n\n/* --- START ${fileName} --- */\n`;
      bundledContent += content;
      bundledContent += `\n/* --- END ${fileName} --- */\n`;
    } else {
      console.warn(`  ! Warning: ${fileName} not found, skipping.`);
    }
  }

  writeFileSync(outputFile, bundledContent);
  console.log(`✅ Success! Bundled file created at: ${outputFile}`);
  console.log(`   Total size: ${(bundledContent.length / 1024).toFixed(2)} KB`);
}

bundle();
